namespace MayazucNativeFramework
{
	runtimeclass VideoEffectProcessorConfiguration
	{
		VideoEffectProcessorConfiguration();

		event Windows.Foundation.EventHandler<String> ConfigurationChanged;

        Boolean MasterSwitch {get; set; };

        Single Brightness{ get; set; };

		Single Contrast{ get; set; };

		Single Saturation{ get; set; };

		Single Temperature{ get; set; };

		Single Tint{ get; set; };

		Single Sharpness{ get; set; };

		Boolean GrayscaleEffect{ get; set; };

		Boolean BlurEffect{ get; set; };
	}

	runtimeclass FrameServerRenderer
	{
		FrameServerRenderer(Microsoft.UI.Xaml.Controls.SwapChainPanel swapChainPannel);

		[default_overload]
		void RenderMediaPlayerFrame(Windows.Media.Playback.MediaPlayer player, Microsoft.UI.Xaml.Controls.Image targetImage, VideoEffectProcessorConfiguration effectConfiguration);
		
		void RenderMediaPlayerFrame(Windows.Media.Playback.MediaPlayer player, Single width, Single height, Single dpi, Windows.Graphics.DirectX.DirectXPixelFormat pixelFormat, VideoEffectProcessorConfiguration effectConfiguration);

		Windows.Foundation.IAsyncAction RenderMediaPlayerFrameToStreamAsync(Windows.Media.Playback.MediaPlayer player, VideoEffectProcessorConfiguration effectConfiguration, Windows.Storage.Streams.IRandomAccessStream outputStream);
	}

	[default_interface]
	runtimeclass SubtitleRenderer
	{
		SubtitleRenderer();

		void RenderSubtitlesToFrame(Windows.Media.Playback.MediaPlaybackItem playbackItem, Microsoft.UI.Xaml.Controls.Image targetImage);
	}
}
